theme: jekyll-theme-tactile
remote_theme: pages-themes/tactile@v0.2.0
title: [bailey's page for techniques class 2025]
description: [this sites purpose is to learn github's markdown language and meet the qualifications of mad's techniques class of 2025]
